title: "Binary Regression Models: An Average Partial Effects Approach"
description: "Replication code for The SAGE Handbook of Quantitative Research Methods in Business & Management"
theme: jekyll-theme-minimal
